"""Drift scan and repair across every app workspace in this OpenSwarm install.

The scan is read-only: it reads text files and stat()s one marker. The repair writes, but only to
files it can prove belong to a sibling workspace, only after the patched shell parses, and only
with a backup on disk it can roll back to.

Preview and apply are the same code path with a flag. That is deliberate: the diff a user approves
is generated by the code that later writes it, so an approved preview cannot disagree with the
result. Nothing here ever restarts another app's runtime — files change, and the user restarts.
"""

import json
import os
import shutil
import subprocess
import tempfile
import time
from contextlib import asynccontextmanager
from typing import Any, Dict, List, Optional

from fastapi import HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from typeguard import typechecked
from swarm_debug import debug

from backend.config.Apps import SubApp
from backend.apps.drift.checks import P_CHECKS, p_grade_workspace
from backend.apps.drift.fixers import P_FIXERS, p_plan


@asynccontextmanager
async def drift_lifespan():
    debug("drift_lifespan START")
    yield
    debug("drift_lifespan END")


drift = SubApp("drift", drift_lifespan)

# This file lives at <ws>/backend/apps/drift/drift.py, so four dirnames up is the workspace and
# five is outputs_workspace/ — the directory holding every app in the install. Deriving it from
# __file__ rather than hardcoding a home path keeps the scan correct on any machine.
P_THIS_WORKSPACE = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
)
P_WORKSPACE_ROOT = os.path.dirname(P_THIS_WORKSPACE)


@typechecked
def p_workspace_name(ws: str) -> str:
    """The app's display name from meta.json, falling back to the workspace id."""
    try:
        with open(os.path.join(ws, "meta.json"), "r", encoding="utf-8") as f:
            meta = json.load(f)
        name = meta.get("name")
        if isinstance(name, str) and name.strip():
            return name.strip()
    except (OSError, json.JSONDecodeError):
        pass
    # No meta.json at all. Showing a bare 32-char hex id reads as corruption; say what it is.
    return f"(unnamed workspace {os.path.basename(ws)[:8]})"


@typechecked
def p_is_workspace(path: str) -> bool:
    """An app workspace, not some unrelated directory that wandered in."""
    if not os.path.isdir(path):
        return False
    return os.path.isdir(os.path.join(path, "frontend")) or os.path.isfile(
        os.path.join(path, "meta.json")
    )


@typechecked
def p_scan() -> List[Dict[str, Any]]:
    apps: List[Dict[str, Any]] = []
    try:
        entries = sorted(os.listdir(P_WORKSPACE_ROOT))
    except OSError:
        return apps

    for entry in entries:
        ws = os.path.join(P_WORKSPACE_ROOT, entry)
        if not p_is_workspace(ws):
            continue
        graded = p_grade_workspace(ws)
        apps.append({
            "id": entry,
            "name": p_workspace_name(ws),
            "path": ws,
            "is_self": os.path.realpath(ws) == os.path.realpath(P_THIS_WORKSPACE),
            "has_backend": os.path.isdir(os.path.join(ws, "backend")),
            "failed": graded["failed"],
            "applicable": graded["applicable"],
            "passed": graded["passed"],
            "checks": graded["checks"],
        })

    # Worst first: the point of the page is triage, not a directory listing.
    apps.sort(key=lambda a: (-int(a["failed"]), str(a["name"]).lower()))
    return apps


# ##################################### Drift Endpoints # #####################################

@drift.router.get("/scan")
@typechecked
async def scan() -> JSONResponse:
    apps = p_scan()
    clean = sum(1 for a in apps if a["failed"] == 0)
    debug(f"drift scan: {len(apps)} workspaces, {clean} clean")
    return JSONResponse({
        "root": P_WORKSPACE_ROOT,
        "total": len(apps),
        "clean": clean,
        "drifted": len(apps) - clean,
        "checks": [
            {"id": c["id"], "label": c["label"], "severity": c["severity"], "fix": c["fix"]}
            for c in P_CHECKS
        ],
        "apps": apps,
    })


# ##################################### Fix # #####################################

class FixRequest(BaseModel):
    app_id: str
    check_ids: Optional[List[str]] = None  # None means "every failing check"
    dry_run: bool = True


@typechecked
def p_resolve_workspace(app_id: str) -> str:
    """Map an app id to its workspace path, refusing anything that escapes the root.

    app_id arrives from the client, so it is treated as hostile. Rejecting separators up front and
    then re-verifying the realpath's parent means neither `../` nor a symlink pointed elsewhere can
    aim a write outside outputs_workspace/.
    """
    if not app_id or os.path.sep in app_id or "/" in app_id or ".." in app_id:
        raise HTTPException(status_code=400, detail="invalid app id")
    ws = os.path.join(P_WORKSPACE_ROOT, app_id)
    real = os.path.realpath(ws)
    if os.path.dirname(real) != os.path.realpath(P_WORKSPACE_ROOT):
        raise HTTPException(status_code=400, detail="app id does not resolve inside the workspace root")
    if not p_is_workspace(real):
        raise HTTPException(status_code=404, detail="no such workspace")
    return real


@typechecked
def p_shell_parses(text: str) -> Optional[str]:
    """None if bash accepts the script, else the parser's complaint.

    An anchored regex that matched slightly wrong can produce a file that looks plausible and is
    unrunnable; an early version of the uvicorn fixer ate a quote and would have left the backend
    unbootable. Nothing reaches disk without clearing this.
    """
    tmp = None
    try:
        with tempfile.NamedTemporaryFile("w", suffix=".sh", delete=False) as fh:
            fh.write(text)
            tmp = fh.name
        proc = subprocess.run(["bash", "-n", tmp], capture_output=True, text=True, timeout=15)
        if proc.returncode == 0:
            return None
        return (proc.stderr or "bash rejected the patched script").strip()[:400]
    except (OSError, subprocess.SubprocessError) as exc:
        return f"could not verify shell syntax: {exc}"
    finally:
        if tmp and os.path.exists(tmp):
            os.unlink(tmp)


@typechecked
def p_toml_parses(text: str) -> Optional[str]:
    """None if the patched TOML parses, else the parser's complaint.

    Earned its place: the first httpx fixer used a non-greedy bracket match, which stopped at the
    `]` inside "fastapi[standard]" and spliced the new entry into the middle of that string. The
    file still looked plausible and every dependency install failed. Shell gets bash -n; TOML needs
    the same gate for the same reason.
    """
    try:
        import tomllib
    except ImportError:  # <3.11 has no stdlib TOML parser; skip rather than block the fix
        return None
    try:
        tomllib.loads(text)
        return None
    except tomllib.TOMLDecodeError as exc:
        return str(exc)[:400]


@drift.router.post("/fix")
@typechecked
async def fix(req: FixRequest) -> JSONResponse:
    ws = p_resolve_workspace(req.app_id)

    graded = p_grade_workspace(ws)
    failing = [c["id"] for c in graded["checks"] if c["state"] == "fail"]
    requested = req.check_ids if req.check_ids is not None else failing

    unknown = [cid for cid in requested if cid not in P_FIXERS]
    if unknown:
        raise HTTPException(status_code=400, detail=f"unknown check ids: {', '.join(unknown)}")
    # Silently ignoring an already-passing check would report a fix that never happened.
    targets = [cid for cid in requested if cid in failing]

    plan = p_plan(ws, targets)
    edits = plan["edits"]

    blocked: List[Dict[str, str]] = []
    for edit in edits:
        if edit.language == "bash":
            problem = p_shell_parses(edit.new_text)
        elif edit.language == "toml":
            problem = p_toml_parses(edit.new_text)
        else:
            problem = None
        if problem:
            blocked.append({"path": edit.rel_path, "problem": problem})

    if blocked:
        debug(f"drift fix REFUSED for {req.app_id}: {blocked}")
        return JSONResponse(
            status_code=422,
            content={
                "applied": False,
                "reason": "the patched script did not parse, so nothing was written",
                "blocked": blocked,
            },
        )

    files = [
        {
            "path": e.rel_path,
            "language": e.language,
            "note": e.note,
            "old_text": e.old_text,
            "new_text": e.new_text,
            "created": e.old_text == "",
        }
        for e in edits
    ]

    if req.dry_run:
        return JSONResponse({
            "applied": False,
            "dry_run": True,
            "app_id": req.app_id,
            "files": files,
            "targets": targets,
            "skipped": plan["skipped"],
        })

    if not edits:
        return JSONResponse({
            "applied": False,
            "app_id": req.app_id,
            "files": [],
            "targets": targets,
            "skipped": plan["skipped"],
            "reason": "nothing to change",
        })

    # Back up every file before touching any of them, so a failure midway through a multi-file
    # write can be undone completely rather than leaving the workspace half-patched.
    stamp = time.strftime("%Y%m%d-%H%M%S")
    backup_dir = os.path.join(ws, ".drift-backup", stamp)
    written: List[str] = []
    try:
        for e in edits:
            src = os.path.join(ws, e.rel_path)
            if os.path.exists(src):
                dst = os.path.join(backup_dir, e.rel_path)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copy2(src, dst)
        for e in edits:
            dest = os.path.join(ws, e.rel_path)
            os.makedirs(os.path.dirname(dest), exist_ok=True)
            with open(dest, "w", encoding="utf-8") as fh:
                fh.write(e.new_text)
            written.append(e.rel_path)
            if e.rel_path.endswith(".sh"):
                os.chmod(dest, 0o755)
            # The marker's whole mechanism is its mtime; writing it without stamping produces a
            # file that passes a glance and fails the check it exists to satisfy.
            if e.set_mtime is not None:
                os.utime(dest, (e.set_mtime, e.set_mtime))
    except OSError as exc:
        for rel in written:
            saved = os.path.join(backup_dir, rel)
            if os.path.exists(saved):
                shutil.copy2(saved, os.path.join(ws, rel))
        debug(f"drift fix FAILED for {req.app_id}, rolled back {len(written)} file(s): {exc}")
        raise HTTPException(status_code=500, detail=f"write failed, rolled back: {exc}")

    after = p_grade_workspace(ws)
    debug(f"drift fix {req.app_id}: {graded['passed']}/{graded['applicable']} -> {after['passed']}/{after['applicable']}")
    return JSONResponse({
        "applied": True,
        "app_id": req.app_id,
        "files": files,
        "targets": targets,
        "skipped": plan["skipped"],
        "backup": os.path.relpath(backup_dir, ws),
        "before": {"passed": graded["passed"], "applicable": graded["applicable"]},
        "after": {"passed": after["passed"], "applicable": after["applicable"]},
        "checks": after["checks"],
    })
